### ISSUE TITLE
Planlagt nedetid i staging

### ISSUE THREAD

**Issue by gunnarvelle** [NDLANO/oppetid#37]
Test for å sjekke banner på undersider.

**Comment by gunnarvelle** [comment]
Fordi denne issuen er tagga med test vil den kunne vises i ndla-frontend i test. Sjekk https://ndla-frontend-pr-911.ndla.sh/ for eksempel.

**Comment by gunnarvelle** [comment]
Dette var ikkje et reellt varsel, kun for å kunne vise banner i midlertidig versjon.

**Comment by ghveem** [comment]
Det er ein bot som lukker saka, ikkje eg på ordentleg..

**Comment by gunnarvelle** [comment]
Skjønte det.
